name: Tests
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - run: |
          git clone --branch 0.5.0 --depth 1 https://github.com/muon-build/muon.git
          cd muon
          ./bootstrap.sh build
          ./build/muon-bootstrap setup build
          ./build/muon-bootstrap -C build samu
          ./build/muon -C build test -R
          sudo ./build/muon -C build install
          cd ..
          rm -rf muon
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install --upgrade pip build
      - run: pip install -e .[dev]
      - run: pytest
